spring:
  main:
    lazy-initialization: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

axon:
  axonserver:
    enabled: false
  eventhandling:
    processors:
      __all__:
        mode: subscribing

logging:
  level:
    com.axians.eaf: DEBUG
    org.axonframework: INFO
