-- ============================================================================
-- Flyway Migration V002: Monthly Partitioning for domain_event_entry
-- ============================================================================
-- Converts the Axon event store table into a declaratively partitioned table
-- using monthly time-based partitions. Partitioning reduces scan size for
-- time-range queries while preserving Axon's default schema semantics.
--
-- Migration Strategy:
--   1. Drop legacy B-tree indexes (replaced by BRIN in V003)
--   2. Rename existing table to domain_event_entry_legacy
--   3. Create new partitioned domain_event_entry table (partition key: time_stamp)
--   4. Create default + current and next 3 month partitions
--   5. Migrate existing data and align identity sequence
--   6. Drop legacy table and sequence
-- ============================================================================

-- Remove legacy indexes created in V001 (replaced by BRIN in V003)
DROP INDEX IF EXISTS idx_domain_event_aggregate;
DROP INDEX IF EXISTS idx_domain_event_timestamp;

-- Preserve existing data by renaming the original table
ALTER TABLE domain_event_entry RENAME TO domain_event_entry_legacy;

-- Rename the legacy sequence to avoid name collisions with the new identity
DO $$
DECLARE
    seq_name TEXT;
    seq_schema TEXT;
    seq_local_name TEXT;
BEGIN
    SELECT pg_get_serial_sequence('domain_event_entry_legacy', 'global_index')
    INTO seq_name;

    IF seq_name IS NOT NULL THEN
        seq_schema := COALESCE(NULLIF(split_part(seq_name, '.', 1), seq_name), 'public');
        seq_local_name := COALESCE(NULLIF(split_part(seq_name, '.', 2), ''), seq_name);

        EXECUTE format(
            'ALTER SEQUENCE %I.%I RENAME TO %I',
            seq_schema,
            seq_local_name,
            seq_local_name || '_legacy'
        );
    END IF;
END $$;

CREATE TABLE domain_event_entry (
    global_index BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregate_identifier VARCHAR(255) NOT NULL,
    sequence_number BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    event_identifier VARCHAR(255) NOT NULL,
    meta_data BYTEA,
    payload BYTEA NOT NULL,
    payload_revision VARCHAR(255),
    payload_type VARCHAR(255) NOT NULL,
    time_stamp VARCHAR(255) NOT NULL,
    PRIMARY KEY (time_stamp, global_index)
) PARTITION BY RANGE (time_stamp);

-- Default partition for legacy or out-of-range events
CREATE TABLE IF NOT EXISTS domain_event_entry_default
    PARTITION OF domain_event_entry
    DEFAULT;

-- Unpartitioned lookup tables for concurrency-safe uniqueness enforcement
-- These tables ensure atomicity via database-level UNIQUE constraints
CREATE TABLE IF NOT EXISTS event_identifier_lookup (
    event_identifier VARCHAR(255) NOT NULL,
    time_stamp VARCHAR(255) NOT NULL,
    global_index BIGINT NOT NULL,
    CONSTRAINT pk_event_identifier_lookup PRIMARY KEY (event_identifier)
);

CREATE TABLE IF NOT EXISTS aggregate_sequence_lookup (
    aggregate_identifier VARCHAR(255) NOT NULL,
    sequence_number BIGINT NOT NULL,
    time_stamp VARCHAR(255) NOT NULL,
    global_index BIGINT NOT NULL,
    CONSTRAINT pk_aggregate_sequence_lookup PRIMARY KEY (aggregate_identifier, sequence_number)
);

-- Create current month + next 3 monthly partitions
DO $$
DECLARE
    start_month DATE := date_trunc('month', now())::date;
    partition_start DATE;
    partition_end DATE;
    partition_name TEXT;
    start_literal TEXT;
    end_literal TEXT;
BEGIN
    FOR i IN 0..3 LOOP
        partition_start := (start_month + (i || ' month')::interval)::date;
        partition_end := (start_month + ((i + 1) || ' month')::interval)::date;
        partition_name := format('domain_event_entry_%s', to_char(partition_start, 'YYYY_MM'));
        start_literal := to_char(partition_start, 'YYYY-MM-01') || 'T00:00:00Z';
        end_literal := to_char(partition_end, 'YYYY-MM-01') || 'T00:00:00Z';

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF domain_event_entry FOR VALUES FROM (%L) TO (%L);',
            partition_name,
            start_literal,
            end_literal
        );
    END LOOP;
END $$;

-- Migrate existing data from the legacy table (if any)
INSERT INTO domain_event_entry (
    global_index,
    aggregate_identifier,
    sequence_number,
    type,
    event_identifier,
    meta_data,
    payload,
    payload_revision,
    payload_type,
    time_stamp
)
SELECT
    global_index,
    aggregate_identifier,
    sequence_number,
    type,
    event_identifier,
    meta_data,
    payload,
    payload_revision,
    payload_type,
    time_stamp
FROM domain_event_entry_legacy;

-- Align the identity sequence with migrated data
WITH seq_info AS (
    SELECT
        pg_get_serial_sequence('domain_event_entry', 'global_index')::regclass AS seq_regclass,
        MAX(global_index) AS max_val
    FROM domain_event_entry
)
SELECT
    CASE
        WHEN seq_info.max_val IS NULL OR seq_info.max_val = 0
            THEN setval(seq_info.seq_regclass, 1, false)
        ELSE setval(seq_info.seq_regclass, seq_info.max_val, true)
    END
FROM seq_info;

-- Concurrency-safe uniqueness enforcement via unpartitioned lookup tables
-- Uses database UNIQUE constraints instead of SELECT checks to prevent TOCTOU race conditions
CREATE OR REPLACE FUNCTION domain_event_entry_enforce_eventidentifier_unique()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    -- INSERT path: Add to lookup table (UNIQUE constraint enforces atomically)
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO event_identifier_lookup (event_identifier, time_stamp, global_index)
        VALUES (NEW.event_identifier, NEW.time_stamp, NEW.global_index);
        -- If duplicate exists, database throws 23505 error automatically
    END IF;

    -- UPDATE path: Remove old entry, add new entry
    IF (TG_OP = 'UPDATE') AND (OLD.event_identifier != NEW.event_identifier) THEN
        DELETE FROM event_identifier_lookup
        WHERE event_identifier = OLD.event_identifier
          AND time_stamp = OLD.time_stamp
          AND global_index = OLD.global_index;

        INSERT INTO event_identifier_lookup (event_identifier, time_stamp, global_index)
        VALUES (NEW.event_identifier, NEW.time_stamp, NEW.global_index);
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION domain_event_entry_enforce_sequence_unique()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    -- INSERT path: Add to lookup table (UNIQUE constraint enforces atomically)
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO aggregate_sequence_lookup (aggregate_identifier, sequence_number, time_stamp, global_index)
        VALUES (NEW.aggregate_identifier, NEW.sequence_number, NEW.time_stamp, NEW.global_index);
        -- If duplicate exists, database throws 23505 error automatically
    END IF;

    -- UPDATE path: Remove old entry, add new entry
    IF (TG_OP = 'UPDATE') AND (OLD.aggregate_identifier != NEW.aggregate_identifier OR OLD.sequence_number != NEW.sequence_number) THEN
        DELETE FROM aggregate_sequence_lookup
        WHERE aggregate_identifier = OLD.aggregate_identifier
          AND sequence_number = OLD.sequence_number
          AND time_stamp = OLD.time_stamp
          AND global_index = OLD.global_index;

        INSERT INTO aggregate_sequence_lookup (aggregate_identifier, sequence_number, time_stamp, global_index)
        VALUES (NEW.aggregate_identifier, NEW.sequence_number, NEW.time_stamp, NEW.global_index);
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_domain_event_identifier_unique ON domain_event_entry;
CREATE TRIGGER trg_domain_event_identifier_unique
    BEFORE INSERT OR UPDATE OF event_identifier
    ON domain_event_entry
    FOR EACH ROW
    EXECUTE FUNCTION domain_event_entry_enforce_eventidentifier_unique();

DROP TRIGGER IF EXISTS trg_domain_event_sequence_unique ON domain_event_entry;
CREATE TRIGGER trg_domain_event_sequence_unique
    BEFORE INSERT OR UPDATE OF aggregate_identifier, sequence_number
    ON domain_event_entry
    FOR EACH ROW
    EXECUTE FUNCTION domain_event_entry_enforce_sequence_unique();

-- Cleanup trigger to remove lookup entries on DELETE
CREATE OR REPLACE FUNCTION domain_event_entry_cleanup_lookups()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM event_identifier_lookup
    WHERE event_identifier = OLD.event_identifier
      AND time_stamp = OLD.time_stamp
      AND global_index = OLD.global_index;

    DELETE FROM aggregate_sequence_lookup
    WHERE aggregate_identifier = OLD.aggregate_identifier
      AND sequence_number = OLD.sequence_number
      AND time_stamp = OLD.time_stamp
      AND global_index = OLD.global_index;

    RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_domain_event_cleanup ON domain_event_entry;
CREATE TRIGGER trg_domain_event_cleanup
    BEFORE DELETE
    ON domain_event_entry
    FOR EACH ROW
    EXECUTE FUNCTION domain_event_entry_cleanup_lookups();

-- Drop the legacy table and sequence remnants
DROP TABLE IF EXISTS domain_event_entry_legacy;
DROP SEQUENCE IF EXISTS domain_event_entry_global_index_seq_legacy;
