-- ============================================================================
-- Flyway Migration V002: Monthly Partitioning for DomainEventEntry
-- ============================================================================
-- Converts the Axon event store table into a declaratively partitioned table
-- using monthly time-based partitions. Partitioning reduces scan size for
-- time-range queries while preserving Axon's default schema semantics.
--
-- Migration Strategy:
--   1. Drop legacy B-tree indexes (replaced by BRIN in V003)
--   2. Rename existing table to DomainEventEntry_legacy
--   3. Create new partitioned DomainEventEntry table (partition key: timeStamp)
--   4. Create default + current and next 3 month partitions
--   5. Migrate existing data and align identity sequence
--   6. Drop legacy table and sequence
-- ============================================================================

-- Remove legacy indexes created in V001 (replaced in V003)
DROP INDEX IF EXISTS idx_domain_event_aggregate;
DROP INDEX IF EXISTS idx_domain_event_timestamp;

-- Preserve existing data by renaming the original table
ALTER TABLE DomainEventEntry RENAME TO DomainEventEntry_legacy;

-- Rename the legacy sequence to avoid name collisions with the new identity
DO $$
DECLARE
    seq_name TEXT;
    seq_schema TEXT;
    seq_local_name TEXT;
BEGIN
    SELECT pg_get_serial_sequence('domainevententry_legacy', 'globalindex')
    INTO seq_name;

    IF seq_name IS NOT NULL THEN
        seq_schema := COALESCE(NULLIF(split_part(seq_name, '.', 1), seq_name), 'public');
        seq_local_name := COALESCE(NULLIF(split_part(seq_name, '.', 2), ''), seq_name);

        EXECUTE format(
            'ALTER SEQUENCE %I.%I RENAME TO %I',
            seq_schema,
            seq_local_name,
            seq_local_name || '_legacy'
        );
    END IF;
END $$;

CREATE TABLE DomainEventEntry (
    globalIndex BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregateIdentifier VARCHAR(255) NOT NULL,
    sequenceNumber BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    eventIdentifier VARCHAR(255) NOT NULL,
    metaData BYTEA,
    payload BYTEA NOT NULL,
    payloadRevision VARCHAR(255),
    payloadType VARCHAR(255) NOT NULL,
    timeStamp VARCHAR(255) NOT NULL,
    PRIMARY KEY (timeStamp, globalIndex)
) PARTITION BY RANGE (timeStamp);

-- Default partition for legacy or out-of-range events
CREATE TABLE IF NOT EXISTS DomainEventEntry_default
    PARTITION OF DomainEventEntry
    DEFAULT;

-- Enforce Axon uniqueness invariants with partition-compatible unique indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_domain_event_identifier_unique
    ON DomainEventEntry (timeStamp, eventIdentifier);

CREATE UNIQUE INDEX IF NOT EXISTS idx_domain_event_sequence_unique
    ON DomainEventEntry (aggregateIdentifier, sequenceNumber, timeStamp);

-- Create current month + next 3 monthly partitions
DO $$
DECLARE
    start_month DATE := date_trunc('month', now())::date;
    partition_start DATE;
    partition_end DATE;
    partition_name TEXT;
    start_literal TEXT;
    end_literal TEXT;
BEGIN
    FOR i IN 0..3 LOOP
        partition_start := (start_month + (i || ' month')::interval)::date;
        partition_end := (start_month + ((i + 1) || ' month')::interval)::date;
        partition_name := format('DomainEventEntry_%s', to_char(partition_start, 'YYYY_MM'));
        start_literal := to_char(partition_start, 'YYYY-MM-01') || 'T00:00:00Z';
        end_literal := to_char(partition_end, 'YYYY-MM-01') || 'T00:00:00Z';

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF DomainEventEntry FOR VALUES FROM (%L) TO (%L);',
            partition_name,
            start_literal,
            end_literal
        );
    END LOOP;
END $$;

-- Migrate existing data from the legacy table (if any)
INSERT INTO DomainEventEntry (
    globalIndex,
    aggregateIdentifier,
    sequenceNumber,
    type,
    eventIdentifier,
    metaData,
    payload,
    payloadRevision,
    payloadType,
    timeStamp
)
SELECT
    globalIndex,
    aggregateIdentifier,
    sequenceNumber,
    type,
    eventIdentifier,
    metaData,
    payload,
    payloadRevision,
    payloadType,
    timeStamp
FROM DomainEventEntry_legacy;

-- Align the identity sequence with migrated data
WITH seq_info AS (
    SELECT
        pg_get_serial_sequence('domainevententry', 'globalindex')::regclass AS seq_regclass,
        MAX(globalIndex) AS max_val
    FROM DomainEventEntry
)
SELECT
    CASE
        WHEN seq_info.max_val IS NULL OR seq_info.max_val = 0
            THEN setval(seq_info.seq_regclass, 1, false)
        ELSE setval(seq_info.seq_regclass, seq_info.max_val, true)
    END
FROM seq_info;

-- Drop the legacy table and sequence remnants
DROP TABLE IF EXISTS DomainEventEntry_legacy;
DROP SEQUENCE IF EXISTS domainevententry_globalindex_seq_legacy;
