-- ============================================================================
-- Flyway Migration V002: Monthly Partitioning for DomainEventEntry
-- ============================================================================
-- Converts the Axon event store table into a declaratively partitioned table
-- using monthly time-based partitions. Partitioning reduces scan size for
-- time-range queries while preserving Axon's default schema semantics.
--
-- Migration Strategy:
--   1. Drop legacy B-tree indexes (replaced by BRIN in V003)
--   2. Rename existing table to DomainEventEntry_legacy
--   3. Create new partitioned DomainEventEntry table (partition key: timeStamp)
--   4. Create default + current and next 3 month partitions
--   5. Migrate existing data and align identity sequence
--   6. Drop legacy table and sequence
-- ============================================================================

-- Remove legacy indexes created in V001 (replaced in V003)
DROP INDEX IF EXISTS idx_domain_event_aggregate;
DROP INDEX IF EXISTS idx_domain_event_timestamp;

-- Preserve existing data by renaming the original table
ALTER TABLE DomainEventEntry RENAME TO DomainEventEntry_legacy;

-- Rename the legacy sequence to avoid name collisions with the new identity
DO $$
DECLARE
    seq_name TEXT;
    seq_schema TEXT;
    seq_local_name TEXT;
BEGIN
    SELECT pg_get_serial_sequence('domainevententry_legacy', 'globalindex')
    INTO seq_name;

    IF seq_name IS NOT NULL THEN
        seq_schema := COALESCE(NULLIF(split_part(seq_name, '.', 1), seq_name), 'public');
        seq_local_name := COALESCE(NULLIF(split_part(seq_name, '.', 2), ''), seq_name);

        EXECUTE format(
            'ALTER SEQUENCE %I.%I RENAME TO %I',
            seq_schema,
            seq_local_name,
            seq_local_name || '_legacy'
        );
    END IF;
END $$;

CREATE TABLE DomainEventEntry (
    globalIndex BIGINT GENERATED BY DEFAULT AS IDENTITY,
    aggregateIdentifier VARCHAR(255) NOT NULL,
    sequenceNumber BIGINT NOT NULL,
    type VARCHAR(255) NOT NULL,
    eventIdentifier VARCHAR(255) NOT NULL,
    metaData BYTEA,
    payload BYTEA NOT NULL,
    payloadRevision VARCHAR(255),
    payloadType VARCHAR(255) NOT NULL,
    timeStamp VARCHAR(255) NOT NULL,
    PRIMARY KEY (timeStamp, globalIndex)
) PARTITION BY RANGE (timeStamp);

-- Default partition for legacy or out-of-range events
CREATE TABLE IF NOT EXISTS DomainEventEntry_default
    PARTITION OF DomainEventEntry
    DEFAULT;

-- Unpartitioned lookup tables for concurrency-safe uniqueness enforcement
-- These tables ensure atomicity via database-level UNIQUE constraints
CREATE TABLE IF NOT EXISTS event_identifier_lookup (
    eventIdentifier VARCHAR(255) NOT NULL,
    timeStamp VARCHAR(255) NOT NULL,
    globalIndex BIGINT NOT NULL,
    CONSTRAINT pk_event_identifier_lookup PRIMARY KEY (eventIdentifier)
);

CREATE TABLE IF NOT EXISTS aggregate_sequence_lookup (
    aggregateIdentifier VARCHAR(255) NOT NULL,
    sequenceNumber BIGINT NOT NULL,
    timeStamp VARCHAR(255) NOT NULL,
    globalIndex BIGINT NOT NULL,
    CONSTRAINT pk_aggregate_sequence_lookup PRIMARY KEY (aggregateIdentifier, sequenceNumber)
);

-- Create current month + next 3 monthly partitions
DO $$
DECLARE
    start_month DATE := date_trunc('month', now())::date;
    partition_start DATE;
    partition_end DATE;
    partition_name TEXT;
    start_literal TEXT;
    end_literal TEXT;
BEGIN
    FOR i IN 0..3 LOOP
        partition_start := (start_month + (i || ' month')::interval)::date;
        partition_end := (start_month + ((i + 1) || ' month')::interval)::date;
        partition_name := format('DomainEventEntry_%s', to_char(partition_start, 'YYYY_MM'));
        start_literal := to_char(partition_start, 'YYYY-MM-01') || 'T00:00:00Z';
        end_literal := to_char(partition_end, 'YYYY-MM-01') || 'T00:00:00Z';

        EXECUTE format(
            'CREATE TABLE IF NOT EXISTS %I PARTITION OF DomainEventEntry FOR VALUES FROM (%L) TO (%L);',
            partition_name,
            start_literal,
            end_literal
        );
    END LOOP;
END $$;

-- Migrate existing data from the legacy table (if any)
INSERT INTO DomainEventEntry (
    globalIndex,
    aggregateIdentifier,
    sequenceNumber,
    type,
    eventIdentifier,
    metaData,
    payload,
    payloadRevision,
    payloadType,
    timeStamp
)
SELECT
    globalIndex,
    aggregateIdentifier,
    sequenceNumber,
    type,
    eventIdentifier,
    metaData,
    payload,
    payloadRevision,
    payloadType,
    timeStamp
FROM DomainEventEntry_legacy;

-- Align the identity sequence with migrated data
WITH seq_info AS (
    SELECT
        pg_get_serial_sequence('domainevententry', 'globalindex')::regclass AS seq_regclass,
        MAX(globalIndex) AS max_val
    FROM DomainEventEntry
)
SELECT
    CASE
        WHEN seq_info.max_val IS NULL OR seq_info.max_val = 0
            THEN setval(seq_info.seq_regclass, 1, false)
        ELSE setval(seq_info.seq_regclass, seq_info.max_val, true)
    END
FROM seq_info;

-- Concurrency-safe uniqueness enforcement via unpartitioned lookup tables
-- Uses database UNIQUE constraints instead of SELECT checks to prevent TOCTOU race conditions
CREATE OR REPLACE FUNCTION domainevententry_enforce_eventidentifier_unique()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    -- INSERT path: Add to lookup table (UNIQUE constraint enforces atomically)
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO event_identifier_lookup (eventIdentifier, timeStamp, globalIndex)
        VALUES (NEW.eventIdentifier, NEW.timeStamp, NEW.globalIndex);
        -- If duplicate exists, database throws 23505 error automatically
    END IF;

    -- UPDATE path: Remove old entry, add new entry
    IF (TG_OP = 'UPDATE') AND (OLD.eventIdentifier != NEW.eventIdentifier) THEN
        DELETE FROM event_identifier_lookup
        WHERE eventIdentifier = OLD.eventIdentifier
          AND timeStamp = OLD.timeStamp
          AND globalIndex = OLD.globalIndex;

        INSERT INTO event_identifier_lookup (eventIdentifier, timeStamp, globalIndex)
        VALUES (NEW.eventIdentifier, NEW.timeStamp, NEW.globalIndex);
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION domainevententry_enforce_sequence_unique()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    -- INSERT path: Add to lookup table (UNIQUE constraint enforces atomically)
    IF (TG_OP = 'INSERT') THEN
        INSERT INTO aggregate_sequence_lookup (aggregateIdentifier, sequenceNumber, timeStamp, globalIndex)
        VALUES (NEW.aggregateIdentifier, NEW.sequenceNumber, NEW.timeStamp, NEW.globalIndex);
        -- If duplicate exists, database throws 23505 error automatically
    END IF;

    -- UPDATE path: Remove old entry, add new entry
    IF (TG_OP = 'UPDATE') AND (OLD.aggregateIdentifier != NEW.aggregateIdentifier OR OLD.sequenceNumber != NEW.sequenceNumber) THEN
        DELETE FROM aggregate_sequence_lookup
        WHERE aggregateIdentifier = OLD.aggregateIdentifier
          AND sequenceNumber = OLD.sequenceNumber
          AND timeStamp = OLD.timeStamp
          AND globalIndex = OLD.globalIndex;

        INSERT INTO aggregate_sequence_lookup (aggregateIdentifier, sequenceNumber, timeStamp, globalIndex)
        VALUES (NEW.aggregateIdentifier, NEW.sequenceNumber, NEW.timeStamp, NEW.globalIndex);
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_domain_event_identifier_unique ON DomainEventEntry;
CREATE TRIGGER trg_domain_event_identifier_unique
    BEFORE INSERT OR UPDATE OF eventIdentifier
    ON DomainEventEntry
    FOR EACH ROW
    EXECUTE FUNCTION domainevententry_enforce_eventidentifier_unique();

DROP TRIGGER IF EXISTS trg_domain_event_sequence_unique ON DomainEventEntry;
CREATE TRIGGER trg_domain_event_sequence_unique
    BEFORE INSERT OR UPDATE OF aggregateIdentifier, sequenceNumber
    ON DomainEventEntry
    FOR EACH ROW
    EXECUTE FUNCTION domainevententry_enforce_sequence_unique();

-- Cleanup trigger to remove lookup entries on DELETE
CREATE OR REPLACE FUNCTION domainevententry_cleanup_lookups()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM event_identifier_lookup
    WHERE eventIdentifier = OLD.eventIdentifier
      AND timeStamp = OLD.timeStamp
      AND globalIndex = OLD.globalIndex;

    DELETE FROM aggregate_sequence_lookup
    WHERE aggregateIdentifier = OLD.aggregateIdentifier
      AND sequenceNumber = OLD.sequenceNumber
      AND timeStamp = OLD.timeStamp
      AND globalIndex = OLD.globalIndex;

    RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_domain_event_cleanup ON DomainEventEntry;
CREATE TRIGGER trg_domain_event_cleanup
    BEFORE DELETE
    ON DomainEventEntry
    FOR EACH ROW
    EXECUTE FUNCTION domainevententry_cleanup_lookups();

-- Drop the legacy table and sequence remnants
DROP TABLE IF EXISTS DomainEventEntry_legacy;
DROP SEQUENCE IF EXISTS domainevententry_globalindex_seq_legacy;
