@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */

package com.axians.eaf.framework.persistence.jooq.tables.references

import com.axians.eaf.framework.persistence.jooq.tables.WidgetView

/**
 * Widget projection table for read queries (CQRS read model)
 */
val WIDGET_VIEW: WidgetView = WidgetView.WIDGET_VIEW
