import { Create, SimpleForm, TextInput, NumberInput, required } from 'react-admin';
import { Typography } from '@mui/material';

/**
 * Widget Create Form
 *
 * Generated by EAF CLI (Story 7.4b)
 * Framework: @axians/eaf-admin-shell v0.1.0
 *
 * Features:
 * - Field grouping with section headings (UX enhancement)
 * - Custom validation messages
 * - Helper text for complex fields
 * - WCAG AA accessible
 */
export const WidgetCreate = () => (
  <Create>
    <SimpleForm>
      <Typography variant="h6" sx={{ mt: 2, mb: 1 }}>
        Basic Information
      </Typography>

      <TextInput
        source="name"
        label="Name"
        validate={required()}
        helperText="Enter widget name"
        fullWidth
      />

      <TextInput
        source="description"
        label="Description"
        helperText="Optional description"
        fullWidth
        multiline
        rows={3}
      />

      <NumberInput
        source="value"
        label="Value"
        validate={required()}
        helperText="Numeric value for the widget"
      />

      <TextInput
        source="category"
        label="Category"
        validate={required()}
        helperText="Widget category"
        fullWidth
      />

      <TextInput
        source="metadata"
        label="Metadata (JSON)"
        helperText="Enter metadata as JSON object"
        fullWidth
        multiline
        rows={2}
      />
    </SimpleForm>
  </Create>
);
