import { Edit, SimpleForm, TextInput, NumberInput, DateTimeInput, required, Toolbar, SaveButton } from 'react-admin';
import { Typography, Box } from '@mui/material';
import { TypeToConfirmDelete } from '@axians/eaf-admin-shell';

/**
 * Widget Edit Form
 *
 * Generated by EAF CLI (Story 7.4b)
 * Framework: @axians/eaf-admin-shell v0.1.0
 *
 * Features:
 * - Optimistic updates (mutationMode="optimistic")
 * - Type-to-confirm delete pattern (prevents accidental deletions)
 * - Undoable delete with 5-second undo
 * - Dirty form detection (warns on navigation)
 */

const EditToolbar = () => (
  <Toolbar sx={{ display: 'flex', justifyContent: 'space-between' }}>
    <TypeToConfirmDelete resource="widget" confirmField="name" />
    <Box>
      <SaveButton />
    </Box>
  </Toolbar>
);

export const WidgetEdit = () => (
  <Edit mutationMode="optimistic">
    <SimpleForm toolbar={<EditToolbar />}>
      <Typography variant="h6" sx={{ mt: 2, mb: 1 }}>
        Basic Information
      </Typography>

      <TextInput
        source="id"
        label="ID"
        disabled
        fullWidth
        helperText="Read-only identifier"
      />

      <TextInput
        source="name"
        label="Name"
        validate={required()}
        fullWidth
      />

      <TextInput
        source="description"
        label="Description"
        fullWidth
        multiline
        rows={3}
      />

      <NumberInput
        source="value"
        label="Value"
        validate={required()}
      />

      <TextInput
        source="category"
        label="Category"
        validate={required()}
        fullWidth
      />

      <TextInput
        source="metadata"
        label="Metadata (JSON)"
        fullWidth
        multiline
        rows={2}
      />

      <DateTimeInput
        source="createdAt"
        label="Created At"
        disabled
        helperText="Read-only creation timestamp"
      />
    </SimpleForm>
  </Edit>
);
