import { Edit, SimpleForm, TextInput, NumberInput, BooleanInput, DateTimeInput, required, Toolbar, SaveButton, DeleteButton } from 'react-admin';
import { Typography, Box } from '@mui/material';
import { TypeToConfirmDelete } from '@axians/eaf-admin-shell';

/**
 * Widget Edit Form
 *
 * Generated by EAF CLI (Story 7.4b)
 * Framework: @axians/eaf-admin-shell v0.1.0
 *
 * Features:
 * - Optimistic updates (mutationMode="optimistic")
 * - Type-to-confirm delete pattern (prevents accidental deletions)
 * - Undoable delete with 5-second undo
 * - Dirty form detection (warns on navigation)
 */

const EditToolbar = () => (
  <Toolbar sx=>
    <TypeToConfirmDelete resource="widget" confirmField="name" />
    <Box>
      <SaveButton />
    </Box>
  </Toolbar>
);

export const WidgetEdit = () => (
  <Edit mutationMode="optimistic">
    <SimpleForm toolbar={<EditToolbar />}>
      <Typography variant="h6" sx=>
        Basic Information
      </Typography>

      <TextInput
        source="id"
        label="Id"
        validate={required()}
        fullWidth
      />
      <NumberInput
        source="id"
        label="Id"
        validate={required()}
      />
      <BooleanInput
        source="id"
        label="Id"
      />
      <DateTimeInput
        source="id"
        label="Id"
        validate={required()}
      />
      <TextInput
        source="name"
        label="Name"
        validate={required()}
        fullWidth
      />
      <NumberInput
        source="name"
        label="Name"
        validate={required()}
      />
      <BooleanInput
        source="name"
        label="Name"
      />
      <DateTimeInput
        source="name"
        label="Name"
        validate={required()}
      />
      <TextInput
        source="description"
        label="Description"
        validate={required()}
        fullWidth
      />
      <NumberInput
        source="description"
        label="Description"
        validate={required()}
      />
      <BooleanInput
        source="description"
        label="Description"
      />
      <DateTimeInput
        source="description"
        label="Description"
        validate={required()}
      />
      <TextInput
        source="value"
        label="Value"
        validate={required()}
        fullWidth
      />
      <NumberInput
        source="value"
        label="Value"
        validate={required()}
      />
      <BooleanInput
        source="value"
        label="Value"
      />
      <DateTimeInput
        source="value"
        label="Value"
        validate={required()}
      />
      <TextInput
        source="category"
        label="Category"
        validate={required()}
        fullWidth
      />
      <NumberInput
        source="category"
        label="Category"
        validate={required()}
      />
      <BooleanInput
        source="category"
        label="Category"
      />
      <DateTimeInput
        source="category"
        label="Category"
        validate={required()}
      />
      <TextInput
        source="metadata"
        label="Metadata"
        validate={required()}
        fullWidth
      />
      <NumberInput
        source="metadata"
        label="Metadata"
        validate={required()}
      />
      <BooleanInput
        source="metadata"
        label="Metadata"
      />
      <DateTimeInput
        source="metadata"
        label="Metadata"
        validate={required()}
      />
      <TextInput
        source="createdAt"
        label="CreatedAt"
        validate={required()}
        fullWidth
      />
      <NumberInput
        source="createdAt"
        label="CreatedAt"
        validate={required()}
      />
      <BooleanInput
        source="createdAt"
        label="CreatedAt"
      />
      <DateTimeInput
        source="createdAt"
        label="CreatedAt"
        validate={required()}
      />
    </SimpleForm>
  </Edit>
);
