import { EmptyState as BaseEmptyState } from '@axians/eaf-admin-shell';

/**
 * Widget Empty State Component
 *
 * Generated by EAF CLI (Story 7.4b)
 *
 * Re-exports framework EmptyState with resource-specific defaults
 */
export const WidgetEmptyState = () => (
  <BaseEmptyState
    message="No widgets yet"
    ctaLabel="Create First Widget"
    ctaLink="/widgets/create"
  />
);
