/**
 * Widget Resource Barrel Exports
 *
 * Generated by EAF CLI (Story 7.4b)
 */
export { WidgetList } from './List';
export { WidgetCreate } from './Create';
export { WidgetEdit } from './Edit';
export { WidgetShow } from './Show';
export { widgetResource } from './ResourceExport';
export type { Widget } from './types';
