import { List, Datagrid, TextField, NumberField, DateField, EditButton } from 'react-admin';
import { EmptyState } from '@axians/eaf-admin-shell';

/**
 * Widget List View
 *
 * Generated by EAF CLI (Story 7.4b)
 * Framework: @axians/eaf-admin-shell v0.1.0
 *
 * Features:
 * - DataGrid with pagination
 * - Filtering by tenant (automatic via dataProvider)
 * - Empty state with CTA
 * - Loading skeleton for perceived performance
 */
export const WidgetList = () => (
  <List
    empty={<EmptyState message="No widgets yet" ctaLabel="Create First Widget" ctaLink="/widgets/create" />}
    perPage={25}
    sort={{ field: 'createdAt', order: 'DESC' }}
  >
    <Datagrid>
      <TextField source="id" label="ID" sortable={false} />
      <TextField source="name" label="Name" />
      <TextField source="description" label="Description" />
      <NumberField source="value" label="Value" />
      <TextField source="category" label="Category" />
      <DateField source="createdAt" label="Created" showTime />
      <EditButton />
    </Datagrid>
  </List>
);
