import { LoadingSkeleton as BaseLoadingSkeleton } from '@axians/eaf-admin-shell';

/**
 * Widget Loading Skeleton Component
 *
 * Generated by EAF CLI (Story 7.4b)
 *
 * Re-exports framework LoadingSkeleton with resource-specific defaults
 */
export const WidgetLoadingSkeleton = () => <BaseLoadingSkeleton rows={5} rowHeight={48} />;
