import { WidgetList } from './List';
import { WidgetCreate } from './Create';
import { WidgetEdit } from './Edit';
import { WidgetShow } from './Show';
import type { ResourceConfig } from '@axians/eaf-admin-shell';

/**
 * Widget Resource Registration
 *
 * Generated by EAF CLI (Story 7.4b)
 *
 * This object is imported by apps/admin for dynamic resource registration:
 * ```
 * import { widgetResource } from '@eaf/product-{module}-ui';
 * <AdminShell resources={[widgetResource]} />
 * ```
 */
export const widgetResource: ResourceConfig = {
  name: 'widgets', // Must match backend @RequestMapping("/widgets")
  list: WidgetList,
  create: WidgetCreate,
  edit: WidgetEdit,
  show: WidgetShow,
};
