import { Show, SimpleShowLayout, TextField, NumberField, BooleanField, DateField } from 'react-admin';
import { Typography } from '@mui/material';

/**
 * Widget Detail View
 *
 * Generated by EAF CLI (Story 7.4b)
 * Framework: @axians/eaf-admin-shell v0.1.0
 *
 * Features:
 * - Section headings for visual hierarchy
 * - Read-only field display
 * - Metadata section (created/updated timestamps)
 */
export const WidgetShow = () => (
  <Show>
    <SimpleShowLayout>
      <Typography variant="h6" sx=>
        Basic Information
      </Typography>

      <TextField source="id" label="ID" />

      <TextField source="id" label="Id" />
      <NumberField source="id" label="Id" />
      <BooleanField source="id" label="Id" />
      <DateField source="id" label="Id" showTime />
      <TextField source="name" label="Name" />
      <NumberField source="name" label="Name" />
      <BooleanField source="name" label="Name" />
      <DateField source="name" label="Name" showTime />
      <TextField source="description" label="Description" />
      <NumberField source="description" label="Description" />
      <BooleanField source="description" label="Description" />
      <DateField source="description" label="Description" showTime />
      <TextField source="value" label="Value" />
      <NumberField source="value" label="Value" />
      <BooleanField source="value" label="Value" />
      <DateField source="value" label="Value" showTime />
      <TextField source="category" label="Category" />
      <NumberField source="category" label="Category" />
      <BooleanField source="category" label="Category" />
      <DateField source="category" label="Category" showTime />
      <TextField source="metadata" label="Metadata" />
      <NumberField source="metadata" label="Metadata" />
      <BooleanField source="metadata" label="Metadata" />
      <DateField source="metadata" label="Metadata" showTime />
      <TextField source="createdAt" label="CreatedAt" />
      <NumberField source="createdAt" label="CreatedAt" />
      <BooleanField source="createdAt" label="CreatedAt" />
      <DateField source="createdAt" label="CreatedAt" showTime />

      <Typography variant="h6" sx=>
        Metadata
      </Typography>

      <DateField source="createdAt" label="Created At" showTime />
      <DateField source="updatedAt" label="Last Updated" showTime />
    </SimpleShowLayout>
  </Show>
);
