import { Show, SimpleShowLayout, TextField, NumberField, DateField } from 'react-admin';
import { Typography } from '@mui/material';

/**
 * Widget Detail View
 *
 * Generated by EAF CLI (Story 7.4b)
 * Framework: @axians/eaf-admin-shell v0.1.0
 *
 * Features:
 * - Section headings for visual hierarchy
 * - Read-only field display
 * - Metadata section (created/updated timestamps)
 */
export const WidgetShow = () => (
  <Show>
    <SimpleShowLayout>
      <Typography variant="h6" sx={{ mt: 2, mb: 1 }}>
        Basic Information
      </Typography>

      <TextField source="id" label="ID" />
      <TextField source="name" label="Name" />
      <TextField source="description" label="Description" />
      <NumberField source="value" label="Value" />
      <TextField source="category" label="Category" />
      <TextField source="metadata" label="Metadata" />

      <Typography variant="h6" sx={{ mt: 3, mb: 1 }}>
        Timestamps
      </Typography>

      <DateField source="createdAt" label="Created At" showTime />
      <DateField source="updatedAt" label="Last Updated" showTime />
    </SimpleShowLayout>
  </Show>
);
