/**
 * Widget TypeScript Interface
 *
 * Generated by EAF CLI (Story 7.4b)
 * Matches backend DTO from shared/shared-api/api/widget/dto/WidgetResponse.kt
 *
 * Field Types (Kotlin → TypeScript mapping):
 * - String → string
 * - BigDecimal → number
 * - Instant → string (ISO 8601 datetime)
 * - Map<String, Any> → Record<string, any>
 */
export interface Widget {
  /** Unique identifier (UUID) */
  id: string;

  /** Widget name */
  name: string;

  /** Optional description */
  description: string | null;

  /** Numeric value (BigDecimal) */
  value: number;

  /** Category classification */
  category: string;

  /** Additional metadata as JSON object */
  metadata: Record<string, any> | null;

  /** Timestamp of creation (ISO 8601 string) */
  createdAt: string;

  /** Timestamp of last update (ISO 8601 string) */
  updatedAt?: string;
}
