/**
 * Widget TypeScript Interface
 *
 * Generated by EAF CLI (Story 7.4b)
 * Matches backend DTO from shared/shared-api/api/widget/dto/
 */
export interface Widget {
  /** Unique identifier (UUID) */
  id: string;

  /** Id field */
  id: string;

  /** Name field */
  name: string;

  /** Description field */
  description: string;

  /** Value field */
  value: string;

  /** Category field */
  category: string;

  /** Metadata field */
  metadata: string;

  /** CreatedAt field */
  createdAt: string;

  /** Timestamp of creation (ISO 8601) */
  createdAt: Date;

  /** Timestamp of last update (ISO 8601) */
  updatedAt: Date;
}
