spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
    lazy-initialization: true  # Fastest startup for testing
  output:
    ansi:
      enabled: never
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
      - org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
  test:
    context:
      cache:
        maxSize: 10  # Optimize context caching for framework tests

# Security framework test configuration
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/test-realm

# EAF Security Configuration (for JWT validation Layer 6)
eaf:
  security:
    jwt:
      expected-issuer: "http://localhost:8080/test-realm"
      expected-audience: "test-audience"

# Framework-specific test properties
framework:
  security:
    test:
      enabled: true
      tenant:
        validation:
          relaxed: true
      performance:
        monitoring: true
        threshold-ms: 5

# Optimized logging for integration tests
logging:
  level:
    root: WARN
    com.axians.eaf.framework.security: DEBUG
    org.springframework.security: INFO  # Reduced from DEBUG for performance
    org.springframework.web: INFO       # Reduced from DEBUG for performance
    org.springframework.boot: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level %logger{20} - %msg%n"