/*
 * This file is generated by jOOQ.
 */
package com.axians.eaf.framework.persistence.jooq

import org.jooq.Constants
import org.jooq.Schema
import org.jooq.impl.CatalogImpl
import kotlin.collections.List

/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DefaultCatalog : CatalogImpl("") {
    companion object {
        /**
         * The reference instance of <code>DEFAULT_CATALOG</code>
         */
        val DEFAULT_CATALOG: DefaultCatalog = DefaultCatalog()
    }

    /**
     * The schema <code>eaf</code>.
     */
    val EAF: Eaf get(): Eaf = Eaf.EAF

    override fun getSchemas(): List<Schema> =
        listOf(
            Eaf.EAF,
        )

    /**
     * A reference to the 3.20 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.20. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private val REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_20
}
