@file:Suppress("ktlint")

/*
 * This file is generated by jOOQ.
 */
package com.axians.eaf.framework.persistence.jooq


import com.axians.eaf.framework.persistence.jooq.tables.WidgetView

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Eaf : SchemaImpl(DSL.name("eaf"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("")) {
    companion object {

        /**
         * The reference instance of <code>eaf</code>
         */
        val EAF: Eaf = Eaf()
    }

    /**
     * Widget projection table for read queries (CQRS read model)
     */
    val WIDGET_VIEW: WidgetView get() = WidgetView.WIDGET_VIEW

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        WidgetView.WIDGET_VIEW
    )
}
