/*
 * This file is generated by jOOQ.
 */
package com.axians.eaf.framework.persistence.jooq.tables.records

import com.axians.eaf.framework.persistence.jooq.tables.WidgetView
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime
import java.util.UUID

/**
 * Widget projection table for read queries (CQRS read model)
 */
@Suppress("warnings")
open class WidgetViewRecord() : UpdatableRecordImpl<WidgetViewRecord>(WidgetView.WIDGET_VIEW) {
    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var published: Boolean?
        set(value): Unit = set(2, value)
        get(): Boolean? = get(2) as Boolean?

    open var createdAt: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    open var updatedAt: OffsetDateTime?
        set(value): Unit = set(4, value)
        get(): OffsetDateTime? = get(4) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised WidgetViewRecord
     */
    constructor(
        id: UUID? = null,
        name: String? = null,
        published: Boolean? = null,
        createdAt: OffsetDateTime? = null,
        updatedAt: OffsetDateTime? = null,
    ) : this() {
        this.id = id
        this.name = name
        this.published = published
        this.createdAt = createdAt
        this.updatedAt = updatedAt
        resetTouchedOnNotNull()
    }
}
