@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */

package com.axians.eaf.framework.persistence.jooq.keys

import com.axians.eaf.framework.persistence.jooq.tables.WidgetView
import com.axians.eaf.framework.persistence.jooq.tables.records.WidgetViewRecord
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal

// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val WIDGET_VIEW_PKEY: UniqueKey<WidgetViewRecord> =
    Internal.createUniqueKey(
        WidgetView.WIDGET_VIEW,
        DSL.name("widget_view_pkey"),
        arrayOf(WidgetView.WIDGET_VIEW.ID),
        true,
    )
