@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */

package com.axians.eaf.framework.persistence.jooq.indexes

import com.axians.eaf.framework.persistence.jooq.tables.WidgetView
import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal

// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_WIDGET_CREATED: Index =
    Internal.createIndex(
        DSL.name("idx_widget_created"),
        WidgetView.WIDGET_VIEW,
        arrayOf(WidgetView.WIDGET_VIEW.CREATED_AT.desc()),
        false,
    )
val IDX_WIDGET_PUBLISHED: Index =
    Internal.createIndex(
        DSL.name("idx_widget_published"),
        WidgetView.WIDGET_VIEW,
        arrayOf(WidgetView.WIDGET_VIEW.PUBLISHED),
        false,
    )
